ALTER TABLE settings 
ADD COLUMN IF NOT EXISTS instagram_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS business_address TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS copyright_text TEXT DEFAULT '© 2026';
